// Pocket AI V3 — Local AI control center. Additive: preserves local-oneclick.js IDs and behavior.
(() => {
  const $=id=>document.getElementById(id), local=$('local'); if(!local||$('localV3Panel')) return;
  const style=document.createElement('style');style.textContent=`
  #local{max-width:1060px}.local-v3-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:16px;margin:18px 0}.local-v3-card{border:1px solid var(--line);border-radius:22px;padding:18px;background:color-mix(in srgb,var(--panel) 94%,transparent);box-shadow:0 10px 32px rgba(65,45,110,.06)}.local-v3-card h3{margin:3px 0 5px}.local-v3-kicker{font-size:10px;letter-spacing:.14em;font-weight:800;color:var(--purple,#8b5cf6)}.local-v3-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.local-v3-stat{padding:11px;border:1px solid var(--line);border-radius:15px}.local-v3-stat small{display:block;color:var(--muted);font-size:10px}.local-v3-stat strong{display:block;margin-top:4px;font-size:12px;overflow:hidden;text-overflow:ellipsis}.local-v3-steps{display:grid;gap:8px;margin-top:13px}.local-v3-step{display:flex;gap:10px;align-items:flex-start;padding:9px 10px;border-radius:14px;background:color-mix(in srgb,var(--purple,#8b5cf6) 5%,transparent)}.local-v3-step b{display:grid;place-items:center;width:22px;height:22px;flex:0 0 22px;border-radius:8px;background:color-mix(in srgb,var(--purple,#8b5cf6) 12%,var(--panel));color:var(--purple,#8b5cf6);font-size:11px}.local-v3-step span{font-size:12px}.local-v3-step small{display:block;color:var(--muted);margin-top:2px}.local-v3-private{display:flex;align-items:center;gap:8px;padding:10px 12px;margin-top:12px;border-radius:14px;background:color-mix(in srgb,#20a86b 8%,var(--panel));border:1px solid color-mix(in srgb,#20a86b 22%,var(--line));font-size:11px}.local-v3-chathead{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:9px}.local-v3-chathead button{font-size:11px;padding:6px 9px}.local-v3-model{display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;border:1px solid var(--line);font-size:10px;color:var(--muted)}#local.local-v3-ready .local-v3-model{color:#16865a;border-color:color-mix(in srgb,#20a86b 35%,var(--line))}#local .device-card,#local #localStatusCard,#local #localProgress,#local #localProgressText,#local .local-actions{max-width:none}.local-v3-card .device-card{margin:0}.local-v3-card #localStatusCard{margin:12px 0 8px}.local-v3-card .local-actions{margin:10px 0 0}.local-v3-card progress{width:100%}.local-v3-chatwrap{margin-top:16px}.local-v3-chatwrap .local-chat{margin:0}.local-v3-chatwrap #localAnswer{min-height:150px;max-height:330px;overflow:auto;white-space:pre-wrap}.local-v3-tip{margin-top:10px;font-size:11px;color:var(--muted)}@media(max-width:760px){.local-v3-grid{grid-template-columns:1fr}.local-v3-stats{grid-template-columns:1fr 1fr}.local-v3-stat:last-child{grid-column:1/-1}}
  `;document.head.appendChild(style);

  const hero=local.querySelector('.hero');
  const panel=document.createElement('div');panel.id='localV3Panel';panel.className='local-v3-grid';
  panel.innerHTML=`<section class="local-v3-card"><span class="local-v3-kicker">PRIVATE ENGINE</span><h3>Local AI control center</h3><p class="muted">Download once, then reconnect from this browser without setting up a server or API key.</p><div id="localV3Mount"></div><div class="local-v3-stats"><div class="local-v3-stat"><small>Model</small><strong id="localV3Model">SmolLM2 360M</strong></div><div class="local-v3-stat"><small>Runs on</small><strong id="localV3Device">This device</strong></div><div class="local-v3-stat"><small>Connection</small><strong id="localV3State">Checking…</strong></div></div><div class="local-v3-private">🔒 <span>Your prompts and model inference stay on this device in Local mode.</span></div></section><aside class="local-v3-card"><span class="local-v3-kicker">HOW IT WORKS</span><h3>Three simple steps</h3><div class="local-v3-steps"><div class="local-v3-step"><b>1</b><span>Setup once<small>Pocket AI downloads a small browser model.</small></span></div><div class="local-v3-step"><b>2</b><span>Connect<small>The saved model is loaded into device memory.</small></span></div><div class="local-v3-step"><b>3</b><span>Chat privately<small>No cloud is used for Local AI responses.</small></span></div></div><p class="local-v3-tip">Tip: Disconnect frees memory but keeps the downloaded model saved for later.</p></aside>`;
  hero?.after(panel);
  const mount=$('localV3Mount');
  const nodes=[local.querySelector('.device-card'),$('localStatusCard'),$('localProgress'),$('localProgressText'),local.querySelector('.local-actions')].filter(Boolean);nodes.forEach(n=>mount.appendChild(n));
  const chat=local.querySelector('.local-chat');if(chat){const wrap=document.createElement('section');wrap.className='local-v3-card local-v3-chatwrap';wrap.innerHTML='<div class="local-v3-chathead"><div><span class="local-v3-kicker">LOCAL CHAT</span><h3>Private conversation</h3></div><span class="local-v3-model">● On-device model</span></div>';chat.before(wrap);wrap.appendChild(chat);}
  const advanced=local.querySelector('.advanced');if(advanced)advanced.querySelector('summary').textContent='⚙ Advanced • Connect a larger model from your own computer/server';

  function sync(){
    const connected=!!window.PocketLocalAI?.isConnected?.(),installed=localStorage.getItem('pocket-local-webllm-installed')==='1';
    local.classList.toggle('local-v3-ready',connected);$('localV3Device').textContent=$('localDevice')?.textContent||'This device';
    $('localV3State').textContent=connected?'Connected':installed?'Saved • ready':'Not installed';
    const badge=local.querySelector('.local-v3-model');if(badge)badge.textContent=connected?'● Connected privately':installed?'○ Model saved':'○ Setup required';
  }
  new MutationObserver(sync).observe(local,{subtree:true,childList:true,characterData:true,attributes:true});
  addEventListener('storage',sync);setInterval(sync,2500);sync();
})();
