/* Pocket AI responsive shell controller */
(()=>{'use strict';
 const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
 const go=id=>{const b=$('[data-go="'+id+'"]');if(b)b.click();else window.PocketV39?.show?.(id)};
 function sidebar(){if($('#paDesktopSidebar'))return;const e=document.createElement('aside');e.id='paDesktopSidebar';e.className='pa-desktop-sidebar';e.innerHTML='<div class="pa-side-brand"><span class="pa-side-logo">◕</span><strong>Pocket AI</strong></div><button class="pa-new-chat" type="button" data-pa-side="chat">＋ New chat</button><small class="pa-side-label">WORKSPACE</small><nav>'+[['home','⌂','Home'],['chat','◉','Chat'],['coding','⌘','Code'],['files','□','Files'],['surface','⌕','Research'],['library','▣','Library'],['study','◇','Study']].map(x=>'<button type="button" data-pa-side="'+x[0]+'"><i>'+x[1]+'</i>'+x[2]+'</button>').join('')+'</nav><div class="pa-side-bottom"><button type="button" data-pa-side="settings"><i>⚙</i>Settings</button><button type="button" data-pa-side="local"><i>●</i><span>Local AI<small>Private engine</small></span></button></div>';document.body.append(e);e.onclick=x=>{const b=x.target.closest('[data-pa-side]');if(!b)return;const id=b.dataset.paSide;if(id==='settings'){$('#settingsDialog')?.showModal?.();return}if(id==='study'){go('chat');setTimeout(()=>$('#v3Study')?.click(),80);return}go(id)};}
 function home(){const g=$('#home>.quick-grid');if(!g)return;const desired=[['chat','💬','Chat','Ask anything'],['research','🔎','Research','Find & explore'],['files','📁','Files','Upload & work'],['code','🧩','Code','Build & create']];desired.forEach(([id,icon,title,sub],i)=>{let b=g.querySelector('[data-quick="'+id+'"]');if(!b){b=document.createElement('button');b.type='button';b.dataset.quick=id;g.append(b)}b.style.order=i;b.hidden=false;b.style.display='';b.innerHTML='<span>'+icon+'</span><strong>'+title+'</strong><small>'+sub+'</small>';b.onclick=()=>id==='research'?go('surface'):id==='code'?go('coding'):go(id)});$$('[data-quick]',g).forEach(b=>{if(!desired.some(x=>x[0]===b.dataset.quick)){b.hidden=true;b.style.display='none'}});}
 function recent(){const a=$('#recentActivity');if(!a)return;const names=['Pride and Prejudice','Research Notes.pdf','Project Plan.docx','Daily Ideas'];const current=$$('.recent-item',a);if(current.length>=4)return;names.forEach((n,i)=>{if(current[i])current[i].querySelector('strong,span')?.replaceChildren(n);else{const b=document.createElement('button');b.className='recent-item';b.type='button';b.innerHTML='<strong>'+n+'</strong><small class="muted">'+(i===3?'Today':'Recently used')+'</small>';a.append(b)}})}
 function sync(){document.documentElement.classList.add('reference-ui-active');sidebar();home();recent();const nav=$('#bottomNav');if(nav)nav.style.display=innerWidth>=768?'none':'';$$('[data-pa-side]').forEach(b=>b.classList.toggle('active',b.dataset.paSide===(($('.view.active')||{}).id||'home')))}
 addEventListener('resize',sync);addEventListener('click',e=>{const b=e.target.closest?.('[data-go]');if(b)setTimeout(sync,0)});addEventListener('pocket-core-ready',sync);addEventListener('pocket-features-ready',sync);if(document.readyState==='loading')addEventListener('DOMContentLoaded',sync,{once:true});else sync();setTimeout(sync,500);setTimeout(sync,1600);
})();
