const fs=require('fs');
const path=require('path');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
const read=f=>fs.readFileSync(path.join(__dirname,f),'utf8');
const index=read('index.html');
const feature=read('feature-v2.js');
const sw=read('sw.js');
const ux=read('ux-v39.js');
const app=read('app.js');
const icons=read('icons-v132.js');
const refs=new Set();
for(const m of index.matchAll(/(?:src|href)=["']\.\/([^"'?]+\.(?:js|css|webmanifest|svg))(?:\?[^"']*)?["']/g))refs.add(m[1]);
for(const m of feature.matchAll(/["']\.\/([^"']+\.(?:js|css))(?:\?[^"']*)?["']/g))refs.add(m[1]);
for(const f of refs)assert(fs.existsSync(path.join(__dirname,f)),'Missing referenced asset: '+f);
for(const f of [...refs].filter(x=>x.endsWith('.js'))){
  try{new Function(read(f))}catch(e){throw new Error('Syntax error in '+f+': '+e.message)}
}
for(const f of refs)assert(sw.includes("'./"+f+"'")||sw.includes('"./'+f+'"'),'Service worker does not precache current asset: '+f);
assert(ux.includes("$$('body > main > .view').forEach"),'Navigation show() must use the multi-element selector');
assert(ux.includes("const views=$$('body > main > .view');"),'Navigation normalization must use the multi-element selector');
assert(app.includes("navigator.serviceWorker.register('./sw.js'"),'Service worker registration is missing');
assert(sw.includes("ignoreSearch:true"),'Offline cache must ignore cache-busting query strings');
assert(sw.includes("event.request.mode==='navigate'"),'Offline HTML fallback must be navigation-only');

assert(index.includes("const BUILD='step21-mobile-ui'"),'STEP 21 build marker is missing');
assert(index.includes('window.__pocketForceBootClose=removeBoot'),'Independent inline boot closer is missing');
assert(index.includes('setTimeout(removeBoot,6500)'),'Independent 6.5s inline boot watchdog is missing');
assert(index.indexOf('setTimeout(removeBoot,6500)')<index.indexOf('src="./boot-v83.js'),'Inline boot watchdog must be defined before external boot-v83.js');
assert(sw.includes("const CACHE=APP_CACHE_PREFIX+'v24'"),'STEP 21 app-shell cache must be v24');
assert(!icons.includes('new MutationObserver(()=>queueMicrotask(run))'),'Dangerous icon MutationObserver microtask loop must not return');
assert(!icons.includes("document.addEventListener('click',()=>queueMicrotask(run)"),'Icon click refresh must not queue run() as a microtask');
assert(icons.includes('function scheduleIconRun()'),'Coalesced icon scheduler is missing');
assert(icons.includes('requestAnimationFrame'),'Icon scheduler must yield to the browser');
assert(icons.includes('function ensureIcon('),'Idempotent icon helper is missing');
assert(index.includes('./icons-v132.js?v=20260925-step12'),'STEP 12 icon cache-bust is missing');
assert(index.includes('data-sound="off"')&&index.includes('data-sound="on"'),'Sound settings controls are missing');
const workspace=read('workspace.js');
assert(workspace.includes("const SOUND_KEY='pocket-sound-v1'"),'Sound storage key is missing');
assert(workspace.includes('function playPocketSound(type)'),'Central Pocket sound API is missing');
assert(workspace.includes('window.AudioContext||window.webkitAudioContext'),'iOS-compatible Web Audio fallback is missing');
assert(workspace.includes("const THEME_CHOICES=new Set(['light','dark','sakura','green','oled'])"),'Authoritative five-theme engine is missing');
assert(workspace.includes('function primePocketAudio()'),'iPhone audio priming hook is missing');
assert(!feature.includes('ui-v59.css'),'Legacy light-only ui-v59.css must not load');
assert(!feature.includes('polish-v84.css'),'Legacy polish-v84.css must not load');
assert(!feature.includes('simple-v87.css'),'Legacy simple-v87.css must not load');
assert(!feature.includes('mobile-v30.css'),'Legacy mobile-v30.css must not load');
assert(!feature.includes("load('./ui-v59.js"),'Legacy ui-v59.js theme engine must not load');
assert(!index.includes('reference-ui-v89.js'),'Legacy reference UI mutator must not load');
assert(!index.includes('photo-ui-v100.js'),'Legacy photo UI mutator must not load');
assert(!index.includes('polish-v84.js'),'Legacy polish UI mutator must not load');
assert(!sw.includes('./ui-v59.css')&&!sw.includes('./ui-v59.js'),'Legacy ui-v59 files must not be precached');
assert(!sw.includes('./reference-ui-v89.js')&&!sw.includes('./photo-ui-v100.js'),'Legacy theme mutators must not be precached');
const ids=[...index.matchAll(/\sid=["']([^"']+)["']/g)].map(m=>m[1]);
const dup=ids.filter((id,i)=>ids.indexOf(id)!==i);
assert(dup.length===0,'Duplicate static IDs: '+[...new Set(dup)].join(', '));
for(const id of ['home','chat','files','local','github','surface','settingsDialog','commandDialog','chatForm','prompt'])assert(ids.includes(id),'Missing core DOM id: '+id);
assert(!ids.includes('bottomNav'),'Bottom navigation must be removed');
const coreCss=read('ui-core.css');
assert(coreCss.includes('STEP 13 — app-wide visual consistency'),'STEP 13 consistency layer is missing');
assert(coreCss.includes('#coding.coding-studio'),'Coding Studio theme bridge is missing');
assert(coreCss.includes('#files .document-studio-v50'),'Files theme bridge is missing');
assert(coreCss.includes('#webNovelHub'),'Web Novel theme bridge is missing');
assert(feature.includes('const FEATURE_BUNDLES='),'Lazy feature bundle map is missing');
assert(feature.includes('function ensureFeatureBundle(name)'),'Lazy feature bundle loader is missing');
assert(feature.includes('requestIdleCallback'),'Idle feature warmup is missing');
assert(!feature.includes('pocket-performance-safe'),'Obsolete performance safe-mode must not return');
assert(!feature.includes("import('./qa-v79.js"),'QA module must not run in production startup');
assert(!sw.includes('./qa-v79.js'),'QA module must not be precached in production shell');
const responsive=read('responsive-v92.js');
const v3=read('v3.js');
const coding=read('coding-v1.js');
assert(!ux.includes('v39More')&&!ux.includes('makeMore()'),'Dead More tools sheet must not return');
assert(ux.includes('window.PocketDialog={open:openDialog,prepare:prepareDialog}'),'Focus-safe dialog helper is missing');
assert(responsive.includes('function setBackgroundInert(on)'),'Mobile drawer background inert handling is missing');
assert(responsive.includes("setAttribute('aria-modal','true')"),'Mobile drawer modal semantics are missing');
assert(responsive.includes("e.key!=='Tab'"),'Mobile drawer focus trap is missing');
assert(index.includes('aria-label="Close Chat AI options"'),'AI dialog close label is missing');
assert(index.includes('aria-label="Close Surface sources"'),'Source dialog close label is missing');
assert(index.includes('aria-label="Close settings"'),'Settings dialog close label is missing');
assert(index.includes('aria-label="Close command palette"'),'Command dialog close label is missing');
assert(v3.includes('id="v3HistoryClose"')&&v3.includes('aria-expanded="false"'),'Accessible Chat history drawer controls are missing');
assert(coding.includes('aria-labelledby="codeProjectDialogTitle"'),'Code projects dialog label is missing');
assert(coreCss.includes('STEP 16 — interaction QA and accessibility'),'STEP 16 touch/focus CSS is missing');
const manifest=JSON.parse(read('manifest.webmanifest'));
assert(app.includes("window.addEventListener('beforeinstallprompt'"),'PWA install prompt handler is missing');
assert(app.includes("window.addEventListener('appinstalled'"),'PWA installed handler is missing');
assert(app.includes("registration.update()")||app.includes("swRegistration.update()"),'Service-worker update check is missing');
assert(app.includes("document.addEventListener('visibilitychange'"),'Visible-app update check is missing');
assert(sw.includes('const CORE_ASSETS=')&&sw.includes('const OPTIONAL_ASSETS='),'Core/optional PWA cache split is missing');
assert(sw.includes('navigationPreload.enable()'),'Navigation preload is missing');
assert(sw.includes("key.startsWith(APP_CACHE_PREFIX)"),'Pocket-owned cache filter is missing');
assert(!/caches\.keys\(\)[\s\S]{0,400}map\([^)]*caches\.delete/.test(index),'Index must not globally delete caches');
assert(manifest.theme_color==='#212121','Manifest theme color is stale');
assert(manifest.background_color==='#f7f8ff','Manifest background color is stale');
assert(Array.isArray(manifest.categories)&&manifest.categories.includes('productivity'),'Manifest categories are missing');
assert(coreCss.includes('STEP 17 — non-overlay install/update shell'),'STEP 17 inline install styling is missing');
assert(!coreCss.includes('#v39More .v39-sheet'),'Dead More sheet selector must not return');
assert(ux.includes('window.PocketNav={show}'),'Canonical PocketNav API is missing');
assert(ux.includes("new CustomEvent('pocket-view-change'"),'Canonical view-change event is missing');
assert(workspace.includes("window.PocketNav?.show?.(id)"),'Workspace must delegate navigation to PocketNav');
assert(responsive.includes("window.PocketNav?.show?.(id)"),'Sidebar must delegate navigation to PocketNav');
assert(responsive.includes("window.addEventListener('pocket-view-change'"),'Sidebar must sync from canonical view changes');
assert(!app.includes('function show(id)'),'app.js must not own navigation anymore');
assert(!app.includes("document.querySelectorAll('[data-go]').forEach"),'app.js must not bind duplicate navigation');
assert(!app.includes("dataset.theme=savedTheme"),'app.js must not own runtime theme state');
assert(!app.includes("$('aiSetup').onclick"),'app.js must not bypass focus-safe AI dialog handling');
assert(!app.includes("$('sourceSetup').onclick"),'app.js must not bypass focus-safe source dialog handling');
assert(!feature.includes("requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}))"),'Feature layer must not duplicate navigation scrolling');
assert(!read('local-oneclick.js').includes('[data-go="local"]'),'Local AI must not duplicate navigation scrolling');
assert(!index.includes('desktop-workspace-v115.js'),'Redundant desktop workspace sync must not load');
assert(!sw.includes('./desktop-workspace-v115.js'),'Redundant desktop workspace sync must not be precached');
assert(!fs.existsSync(path.join(__dirname,'desktop-workspace-v115.js')),'Redundant desktop workspace sync file must stay removed');
const chatCss=read('chat-v77.css');
const v3Css=read('v3.css');
const files31Css=read('files-v31.css');
const files80Css=read('files-v80.css');
const libraryCss=read('library-v33.css');
const importantCount=s=>(s.match(/!important/g)||[]).length;
assert(!fs.existsSync(path.join(__dirname,'v3-hotfix.css')),'Dead v3-hotfix.css must stay removed');
assert(!fs.existsSync(path.join(__dirname,'visibility-v82.css')),'Dead visibility-v82.css must stay removed');
assert(!feature.includes('v3-hotfix.css')&&!feature.includes('visibility-v82.css'),'Deleted compatibility CSS must not be loaded');
assert(!sw.includes('v3-hotfix.css')&&!sw.includes('visibility-v82.css'),'Deleted compatibility CSS must not be precached');
assert(!chatCss.includes('bottomNav')&&!chatCss.includes('pocket-v59'),'Chat CSS must not contain deleted navigation/theme compatibility selectors');
assert(chatCss.includes('bottom:auto!important'),'Mobile Chat composer must not reserve deleted bottom-nav space');
assert(chatCss.includes('position:relative!important')&&chatCss.includes('top:auto!important'),'Mobile Chat controls must not stick under the global header');
const responsiveCssJs=read('responsive-v92.js');
assert(!responsiveCssJs.includes("($('#prompt')||$('#v3NewChat'))?.focus"),'Mobile Chat navigation must not auto-focus the composer');
assert(responsiveCssJs.includes("$('#v3ChatTitle')"),'Mobile Chat navigation should focus the Chat heading');
assert(chatCss.includes('scroll-margin-top:64px'),'Mobile Chat controls need header-safe scroll margin');
assert(!files80Css.includes('132px')&&!files80Css.includes('120px!important'),'Files must not reserve deleted bottom-nav clearance');
assert(!libraryCss.includes('150px!important')&&!libraryCss.includes('98px!important'),'Library must not reserve deleted bottom-nav clearance');
assert(coreCss.includes('Authoritative workspace visibility'),'Workspace visibility must live in ui-core.css');
assert(coreCss.includes('STEP 21 — authoritative mobile Home layout'),'STEP 21 mobile Home block is missing');
assert(!coreCss.includes('STEP 10 — Mobile Home composition cleanup'),'Obsolete STEP 10 mobile patch must stay removed');
assert((coreCss.match(/STEP 21 — authoritative mobile Home layout/g)||[]).length===1,'STEP 21 mobile Home layout must have a single owner');
assert(coreCss.includes('#home .pocket-room{')&&coreCss.includes('height:220px'),'STEP 21 Pocket Room sizing is missing');
assert(coreCss.includes('@media(max-width:340px)')&&coreCss.includes('#home .quick-grid{grid-template-columns:1fr}'),'320px quick-action fallback is missing');
assert(/\.topbar\{position:relative;z-index:140;[^}]*display:flex;[^}]*align-items:center;/.test(coreCss),'One-line header layout fix is missing');
assert(ux.includes("const FEATURE_FOR_VIEW={coding:'coding',files:'files',library:'library'}"),'Lazy feature navigation map is missing');
assert(ux.includes("ensure(feature).then(()=>show(id))"),'First-tap lazy navigation recovery is missing');
assert(importantCount(v3Css)<=13,'v3.css !important budget regressed');
assert(importantCount(chatCss)<=184,'chat-v77.css !important budget regressed');
assert(importantCount(files31Css)===0,'files-v31.css should not need !important');
assert(importantCount(files80Css)<=139,'files-v80.css !important budget regressed');
assert(importantCount(libraryCss)<=74,'library-v33.css !important budget regressed');
const removedLegacy=["buttons-v128.css","cards-v130.css","cards-v131.css","chat-v134.css","colors-v127.css","desktop-v97.css","desktop-workspace-v115.css","header-v119.css","home-step1-v117.css","home-v44.css","home-v45.css","layout-v56.css","mobile-ui-fix-v47.css","mobile-v133.css","mobile-v30.css","nav-fix-v61.css","panels-v2.css","personality-v135.css","photo-ui-v100.css","photo-ui-v100.js","polish-v84.css","polish-v84.js","polish.css","reference-ui-v57.css","reference-ui-v57.js","reference-ui-v58.css","reference-ui-v58.js","reference-ui-v89.css","reference-ui-v89.js","responsive-v92.css","simple-v87.css","soft-ui-v55.css","styles.css","surfaces-v129.css","typography-v126.css","ui-v55.js","ui-v59.css","ui-v59.js","ux-v36.css","ux-v36.js","ux-v37.css","ux-v37.js","ux-v38.css","ux-v38.js","ux-v39.css","ux-v41.css","ux-v43.css","home-v43.js","repair-v56.js"];
for(const f of removedLegacy)assert(!fs.existsSync(path.join(__dirname,f)),'Removed legacy file returned: '+f);

assert(!index.includes('data-theme-choice="system"'),'Duplicate System theme option must be removed');
assert(!/[>](?:💬|🎓|⌘|▱|⌕|▦|⌂)[<]/.test(responsive),'Drawer must not contain legacy duplicate glyph icons');
console.log('Pocket AI smoke checks passed:',refs.size,'current assets verified.');
