const fs=require('fs');
const path=require('path');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
const read=f=>fs.readFileSync(path.join(__dirname,f),'utf8');
const index=read('index.html');
const feature=read('feature-v2.js');
const sw=read('sw.js');
const ux=read('ux-v39.js');
const app=read('app.js');
const icons=read('icons-v132.js');
const refs=new Set();
for(const m of index.matchAll(/(?:src|href)=["']\.\/([^"'?]+\.(?:js|css|webmanifest|svg))(?:\?[^"']*)?["']/g))refs.add(m[1]);
for(const m of feature.matchAll(/["']\.\/([^"']+\.(?:js|css))(?:\?[^"']*)?["']/g))refs.add(m[1]);
for(const f of refs)assert(fs.existsSync(path.join(__dirname,f)),'Missing referenced asset: '+f);
for(const f of [...refs].filter(x=>x.endsWith('.js'))){
  try{new Function(read(f))}catch(e){throw new Error('Syntax error in '+f+': '+e.message)}
}
for(const f of refs)assert(sw.includes("'./"+f+"'")||sw.includes('"./'+f+'"'),'Service worker does not precache current asset: '+f);
assert(ux.includes("$$('body > main > .view').forEach"),'Navigation show() must use the multi-element selector');
assert(ux.includes("const views=$$('body > main > .view');"),'Navigation normalization must use the multi-element selector');
assert(app.includes("navigator.serviceWorker.register('./sw.js'"),'Service worker registration is missing');
assert(sw.includes("ignoreSearch:true"),'Offline cache must ignore cache-busting query strings');
assert(sw.includes("event.request.mode==='navigate'"),'Offline HTML fallback must be navigation-only');

assert(index.includes("const BUILD='step15-performance'"),'STEP 15 build marker is missing');
assert(index.includes('window.__pocketForceBootClose=removeBoot'),'Independent inline boot closer is missing');
assert(index.includes('setTimeout(removeBoot,6500)'),'Independent 6.5s inline boot watchdog is missing');
assert(index.indexOf('setTimeout(removeBoot,6500)')<index.indexOf('src="./boot-v83.js'),'Inline boot watchdog must be defined before external boot-v83.js');
assert(sw.includes("const CACHE=APP_CACHE_PREFIX+'v14'"),'STEP 15 app-shell cache must be v14');
assert(!icons.includes('new MutationObserver(()=>queueMicrotask(run))'),'Dangerous icon MutationObserver microtask loop must not return');
assert(!icons.includes("document.addEventListener('click',()=>queueMicrotask(run)"),'Icon click refresh must not queue run() as a microtask');
assert(icons.includes('function scheduleIconRun()'),'Coalesced icon scheduler is missing');
assert(icons.includes('requestAnimationFrame'),'Icon scheduler must yield to the browser');
assert(icons.includes('function ensureIcon('),'Idempotent icon helper is missing');
assert(index.includes('./icons-v132.js?v=20260925-step12'),'STEP 12 icon cache-bust is missing');
assert(index.includes('data-sound="off"')&&index.includes('data-sound="on"'),'Sound settings controls are missing');
const workspace=read('workspace.js');
assert(workspace.includes("const SOUND_KEY='pocket-sound-v1'"),'Sound storage key is missing');
assert(workspace.includes('function playPocketSound(type)'),'Central Pocket sound API is missing');
assert(workspace.includes('window.AudioContext||window.webkitAudioContext'),'iOS-compatible Web Audio fallback is missing');
assert(workspace.includes("const THEME_CHOICES=new Set(['light','dark','sakura','green','oled'])"),'Authoritative five-theme engine is missing');
assert(workspace.includes('function primePocketAudio()'),'iPhone audio priming hook is missing');
assert(!feature.includes('ui-v59.css'),'Legacy light-only ui-v59.css must not load');
assert(!feature.includes('polish-v84.css'),'Legacy polish-v84.css must not load');
assert(!feature.includes('simple-v87.css'),'Legacy simple-v87.css must not load');
assert(!feature.includes('mobile-v30.css'),'Legacy mobile-v30.css must not load');
assert(!feature.includes("load('./ui-v59.js"),'Legacy ui-v59.js theme engine must not load');
assert(!index.includes('reference-ui-v89.js'),'Legacy reference UI mutator must not load');
assert(!index.includes('photo-ui-v100.js'),'Legacy photo UI mutator must not load');
assert(!index.includes('polish-v84.js'),'Legacy polish UI mutator must not load');
assert(!sw.includes('./ui-v59.css')&&!sw.includes('./ui-v59.js'),'Legacy ui-v59 files must not be precached');
assert(!sw.includes('./reference-ui-v89.js')&&!sw.includes('./photo-ui-v100.js'),'Legacy theme mutators must not be precached');
const ids=[...index.matchAll(/\sid=["']([^"']+)["']/g)].map(m=>m[1]);
const dup=ids.filter((id,i)=>ids.indexOf(id)!==i);
assert(dup.length===0,'Duplicate static IDs: '+[...new Set(dup)].join(', '));
for(const id of ['home','chat','files','local','github','surface','settingsDialog','commandDialog','chatForm','prompt'])assert(ids.includes(id),'Missing core DOM id: '+id);
assert(!ids.includes('bottomNav'),'Bottom navigation must be removed');
const coreCss=read('ui-core.css');
assert(coreCss.includes('STEP 13 — app-wide visual consistency'),'STEP 13 consistency layer is missing');
assert(coreCss.includes('#coding.coding-studio'),'Coding Studio theme bridge is missing');
assert(coreCss.includes('#files .document-studio-v50'),'Files theme bridge is missing');
assert(coreCss.includes('#webNovelHub'),'Web Novel theme bridge is missing');
assert(feature.includes('const FEATURE_BUNDLES='),'Lazy feature bundle map is missing');
assert(feature.includes('function ensureFeatureBundle(name)'),'Lazy feature bundle loader is missing');
assert(feature.includes('requestIdleCallback'),'Idle feature warmup is missing');
assert(!feature.includes('pocket-performance-safe'),'Obsolete performance safe-mode must not return');
assert(!feature.includes("import('./qa-v79.js"),'QA module must not run in production startup');
assert(!sw.includes('./qa-v79.js'),'QA module must not be precached in production shell');
const removedLegacy=["buttons-v128.css","cards-v130.css","cards-v131.css","chat-v134.css","colors-v127.css","desktop-v97.css","desktop-workspace-v115.css","header-v119.css","home-step1-v117.css","home-v44.css","home-v45.css","layout-v56.css","mobile-ui-fix-v47.css","mobile-v133.css","mobile-v30.css","nav-fix-v61.css","panels-v2.css","personality-v135.css","photo-ui-v100.css","photo-ui-v100.js","polish-v84.css","polish-v84.js","polish.css","reference-ui-v57.css","reference-ui-v57.js","reference-ui-v58.css","reference-ui-v58.js","reference-ui-v89.css","reference-ui-v89.js","responsive-v92.css","simple-v87.css","soft-ui-v55.css","styles.css","surfaces-v129.css","typography-v126.css","ui-v55.js","ui-v59.css","ui-v59.js","ux-v36.css","ux-v36.js","ux-v37.css","ux-v37.js","ux-v38.css","ux-v38.js","ux-v39.css","ux-v41.css","ux-v43.css","home-v43.js","repair-v56.js"];
for(const f of removedLegacy)assert(!fs.existsSync(path.join(__dirname,f)),'Removed legacy file returned: '+f);

assert(!index.includes('data-theme-choice="system"'),'Duplicate System theme option must be removed');
const responsive=read('responsive-v92.js');
assert(!/[>](?:💬|🎓|⌘|▱|⌕|▦|⌂)[<]/.test(responsive),'Drawer must not contain legacy duplicate glyph icons');
console.log('Pocket AI smoke checks passed:',refs.size,'current assets verified.');
